---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: testing
  pull: always
  image: golang:1.12
  commands:
  - go test -v .
  environment:
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org
  volumes:
  - name: gopath
    path: /go
